name: "nakama"                   # Server name
transport:
  grpc_port: 7349                 # gRPC API port
  http_key: "defaultkey"          # HTTP API authentication key
logger:
  level: "debug"                   # Log level (debug, info, warn, error)
database:
  address:
    - "postgres:localdb@postgres:5432/nakama"  # PostgreSQL database
  user: "postgres"
  password: "localdb"
  name: "nakama"
  max_open_conns: 100
  max_idle_conns: 25
console:
  port: 7351                      # Nakama Developer Console port
  username: "admin"
  password: "password"
runtime:
  path: "/nakama/data/modules"    # Path to Lua modules
  http_key: "runtime-key"
  lua:
    entrypoint: "main.lua"        # Lua entry point
session:
  token_expiry_sec: 31536000         # Session token expiration (1 year, effectively never)
socket:
  port: 7350                      # WebSocket API port
auth:
  device:
    enabled: true
  email:
    enabled: true
  custom:
    enabled: true